### ISSUE TITLE
소진 마지막 작업 

### ISSUE THREAD

**Issue by 513sojin** [Team-Ming/Ming-iOS#10]
## ToDo
- [x] 확인 버튼 누를 시 뷰에 추가 

## Develop
- [ ] 데이터가 없을때 empty view 만들기
- [ ] 데이터가 없을때 버튼 비활성화
