### ISSUE TITLE
'오늘의 확인' 기적 확인뷰, 팝업창 구현

### ISSUE THREAD

**Issue by ffalswo2** [Team-Ming/Ming-iOS#2]
## 💡 Feature Issue

확인뷰와 말풍선 클릭뷰 구현

## 🌿  To-do

- [ ] '오늘의 기적' 확인뷰 UI 구현
- [ ] 팝업창 구현
- [ ] 팝업창에서 입력한 text값 같으면 data 지우기
- [ ] '오늘의 기적' 없을시 화면전환
